version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mauro
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"

